name: Secret Management Demo

on: [push]

jobs:
  reveal-secrets:
    runs-on: ubuntu-latest

    env:
      USER_FROM_SECRET: ${{ secrets.USERNAME }}
      API_KEY_SECRET: ${{ secrets.API_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print Secrets (safe way)
        run: |
          echo "Using USERNAME: $USER_FROM_SECRET"
          echo "Using API_KEY: $API_KEY_SECRET"
